// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1cBbodYKKdeH7nKzU3mO5E1tfi5JwwIk',
    appId: '1:267920119442:android:db30fe5b4361268cfc784b',
    messagingSenderId: '267920119442',
    projectId: 'sprints-project',
    storageBucket: 'sprints-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRYsAlwvCEKFUeWafw2OdEn-UJA_6Snng',
    appId: '1:267920119442:ios:a9276c2b0d441836fc784b',
    messagingSenderId: '267920119442',
    projectId: 'sprints-project',
    storageBucket: 'sprints-project.firebasestorage.app',
    iosBundleId: 'com.example.sprintsFirebaseTasks',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaN5vEperMQ95dG06xe6EbGkAs1xqao6g',
    appId: '1:267920119442:web:a9a7aa5071a7cb4efc784b',
    messagingSenderId: '267920119442',
    projectId: 'sprints-project',
    authDomain: 'sprints-project.firebaseapp.com',
    storageBucket: 'sprints-project.firebasestorage.app',
    measurementId: 'G-X6NWWNQW2M',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRYsAlwvCEKFUeWafw2OdEn-UJA_6Snng',
    appId: '1:267920119442:ios:a9276c2b0d441836fc784b',
    messagingSenderId: '267920119442',
    projectId: 'sprints-project',
    storageBucket: 'sprints-project.firebasestorage.app',
    iosBundleId: 'com.example.sprintsFirebaseTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaN5vEperMQ95dG06xe6EbGkAs1xqao6g',
    appId: '1:267920119442:web:e36768751c1df28afc784b',
    messagingSenderId: '267920119442',
    projectId: 'sprints-project',
    authDomain: 'sprints-project.firebaseapp.com',
    storageBucket: 'sprints-project.firebasestorage.app',
    measurementId: 'G-NEYFHFZHSJ',
  );

}